/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.informatica.util;

import br.com.informatica.dal.Conexao;
import br.com.informatica.telas.GerarBoleto;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author edilson
 */
public class AlterarBoletoDialog extends javax.swing.JDialog {

    public static GerarBoleto boleto;
    String codigo,status,vencimento,prestacao,quantPrest,pagador,cpf,rua,quad,lote,loteamento,cidade,CN;
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public AlterarBoletoDialog(GerarBoleto parent, boolean modal) {
        this.boleto = parent;
        this.setModal(modal);
        initComponents();
      // pesquisarBoleto();
      txtPesquisaBoleto.requestFocus();
        conexao = Conexao.conector;
    }

    public String getCodigo() {

        return codigo;
    }

    public String getStatus() {
        return status;
    }

    public String getCN() {
        return CN;
    }
   

    public String getVencimento() {
        return vencimento;
    }

    public String getPrestacao() {
        return prestacao;
    }

    public String getQuantPrest() {
        return quantPrest;
    }
    
    public String getPagador() {
        return pagador;
    }

    public String getCpf() {
        return cpf;
    }

    public String getRua() {
        return rua;
    }

    public String getQuad() {
        return quad;
    }

    public String getLote() {
        return lote;
    }

    public String getLoteamento() {
        return loteamento;
    }

    public String getCidade() {
        return cidade;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBoleto = new javax.swing.JTable();
        jBnFechar = new javax.swing.JButton();
        jBnInserir = new javax.swing.JButton();
        txtPesquisaBoleto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 240, 240));

        jTableBoleto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "status", "CN", "Venc", "Prest", "QuantPrest", "pagador", "cpf", "rua", "quad", "lote", "loteam", "cidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBoleto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBoletoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBoleto);

        jBnFechar.setBackground(new java.awt.Color(204, 240, 240));
        jBnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/informatica/icones/fechar2.png"))); // NOI18N
        jBnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnFecharActionPerformed(evt);
            }
        });

        jBnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/informatica/icones/inserir.png"))); // NOI18N
        jBnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnInserirActionPerformed(evt);
            }
        });

        txtPesquisaBoleto.setToolTipText("Digite o nome ou clique na barra de espaço");
        txtPesquisaBoleto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaBoletoKeyReleased(evt);
            }
        });

        jLabel9.setText("Pesquisar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPesquisaBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jBnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jBnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtPesquisaBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableBoletoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBoletoMouseClicked
        int setar = jTableBoleto.getSelectedRow();
        codigo = (jTableBoleto.getModel().getValueAt(setar, 0).toString());System.out.println("codigo "+codigo);
        status = (jTableBoleto.getModel().getValueAt(setar, 1).toString());System.out.println("status  "+status);
        CN = (jTableBoleto.getModel().getValueAt(setar, 2).toString());System.out.println("CN   "+CN);
        vencimento = (jTableBoleto.getModel().getValueAt(setar, 3).toString());System.out.println("VENCIMENTO "+vencimento);
        prestacao = (jTableBoleto.getModel().getValueAt(setar, 4).toString());System.out.println("prestacao "+prestacao);
        quantPrest = (jTableBoleto.getModel().getValueAt(setar, 5).toString());System.out.println("Quante prestacao "+quantPrest);
        
        pagador = (jTableBoleto.getModel().getValueAt(setar, 6).toString());System.out.println("pagador "+pagador);
        cpf = (jTableBoleto.getModel().getValueAt(setar, 7).toString());System.out.println("cpf "+cpf);
        rua = (jTableBoleto.getModel().getValueAt(setar, 8).toString());System.out.println("rua "+rua);
        quad = (jTableBoleto.getModel().getValueAt(setar, 9).toString());System.out.println("quadra "+quad);
        lote = (jTableBoleto.getModel().getValueAt(setar, 10).toString());System.out.println("lote "+lote);
        loteamento = (jTableBoleto.getModel().getValueAt(setar, 11).toString());System.out.println("loteamento "+loteamento);
        cidade = (jTableBoleto.getModel().getValueAt(setar, 12).toString());System.out.println("cidade "+cidade);
    }//GEN-LAST:event_jTableBoletoMouseClicked

    private void jBnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBnFecharActionPerformed

    private void jBnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnInserirActionPerformed

        this.dispose();
        GerarBoleto gerarBoleto = new GerarBoleto();
        gerarBoleto.jBtInserir.setEnabled(false);

    }//GEN-LAST:event_jBnInserirActionPerformed

    private void txtPesquisaBoletoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaBoletoKeyReleased
        pesquisarBoleto();
    }//GEN-LAST:event_txtPesquisaBoletoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarBoletoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarBoletoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarBoletoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarBoletoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlterarBoletoDialog dialog = new AlterarBoletoDialog(boleto, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBnFechar;
    private javax.swing.JButton jBnInserir;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBoleto;
    private javax.swing.JTextField txtPesquisaBoleto;
    // End of variables declaration//GEN-END:variables
   private void pesquisarBoleto() {
        String sql = "select codBoleto,status,CN,dataVenc,valorIntegral,quantPrest,pagador,cpf,rua,quadra,lote,loteamento,cidade from boleto where pagador LIKE ?";
        GerarBoleto gerarBoleto = new GerarBoleto();
        try {

         //  String pesquisaBoleto = gerarBoleto.jTextPesqPagador.getText();
            pst = conexao.prepareStatement(sql);
         
           pst.setString(1, "%"+txtPesquisaBoleto.getText()+"%");
        //    pst.setString(1, "%"+pesquisaBoleto+"%");
            rs = pst.executeQuery();
            jTableBoleto.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
}