/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.informatica.util;

import br.com.informatica.telas.TelaImovel;
import br.com.informatica.dal.Conexao;
import br.com.informatica.telas.TelaPrincipal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author edilson
 */
public class DialogLoteamento extends javax.swing.JDialog {
Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public DialogLoteamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        conexao = Conexao.conector;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNomeLoteamento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSetorLoteamento = new javax.swing.JTextField();
        txtEstadoLoteamento = new javax.swing.JTextField();
        txtCidadeLoteamento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoteamento = new javax.swing.JTable();
        txtPesquisarLoteamento = new javax.swing.JTextField();
        btnInserirLoteamento = new javax.swing.JButton();
        txtCodLoteamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboULoteamento = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 240, 240));

        jLabel2.setText("Nome Lot");

        jLabel4.setText("Setor");

        txtSetorLoteamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetorLoteamentoActionPerformed(evt);
            }
        });

        txtEstadoLoteamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoLoteamentoActionPerformed(evt);
            }
        });

        tblLoteamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod Loteamento", "Nome Loteamento", "Setor Lotea", "Cidade", "Estado", "UF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoteamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoteamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoteamento);

        txtPesquisarLoteamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarLoteamentoKeyReleased(evt);
            }
        });

        btnInserirLoteamento.setBackground(new java.awt.Color(102, 102, 255));
        btnInserirLoteamento.setText("Inserir");
        btnInserirLoteamento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInserirLoteamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirLoteamentoActionPerformed(evt);
            }
        });

        txtCodLoteamento.setEnabled(false);

        jLabel1.setText("COD Lote");

        jLabel3.setText("Cidade");

        jLabel6.setText("UF");

        cboULoteamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(txtPesquisarLoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnInserirLoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(456, 456, 456))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCodLoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeLoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSetorLoteamento))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCidadeLoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(txtEstadoLoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboULoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtCodLoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSetorLoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeLoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCidadeLoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoLoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cboULoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarLoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserirLoteamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSetorLoteamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetorLoteamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetorLoteamentoActionPerformed

    private void txtEstadoLoteamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoLoteamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoLoteamentoActionPerformed

    private void tblLoteamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoteamentoMouseClicked
//        btnCadastrarLoteamento.setEnabled(false);
//        btnAlterarLoteamento.setEnabled(true);
//        btnExcluirLoteamento.setEnabled(true);
       setarCamposLoteamento();
    }//GEN-LAST:event_tblLoteamentoMouseClicked

    private void txtPesquisarLoteamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarLoteamentoKeyReleased
        pesquisarLoteamento();
    }//GEN-LAST:event_txtPesquisarLoteamentoKeyReleased

    private void btnInserirLoteamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirLoteamentoActionPerformed
          verificarCodLoteamento();
    }//GEN-LAST:event_btnInserirLoteamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogLoteamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogLoteamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogLoteamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogLoteamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogLoteamento dialog = new DialogLoteamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnInserirLoteamento;
    private javax.swing.JComboBox<String> cboULoteamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLoteamento;
    private javax.swing.JTextField txtCidadeLoteamento;
    private javax.swing.JTextField txtCodLoteamento;
    private javax.swing.JTextField txtEstadoLoteamento;
    private javax.swing.JTextField txtNomeLoteamento;
    private javax.swing.JTextField txtPesquisarLoteamento;
    private javax.swing.JTextField txtSetorLoteamento;
    // End of variables declaration//GEN-END:variables
 public void pesquisarLoteamento() {
        String sql = "select * from loteamento where nomeLoteamento LIKE ? ORDER BY nomeLoteamento";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, "%" + txtPesquisarLoteamento.getText() + "%");
            rs = pst.executeQuery();
            tblLoteamento.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void setarCamposLoteamento() {
          int setar = tblLoteamento.getSelectedRow();
        txtCodLoteamento.setText(tblLoteamento.getModel().getValueAt(setar, 0).toString());
        txtNomeLoteamento.setText(tblLoteamento.getModel().getValueAt(setar, 1).toString());
        txtSetorLoteamento.setText(tblLoteamento.getModel().getValueAt(setar, 2).toString());
        txtCidadeLoteamento.setText(tblLoteamento.getModel().getValueAt(setar, 3).toString());
        txtEstadoLoteamento.setText(tblLoteamento.getModel().getValueAt(setar, 4).toString());
        cboULoteamento.setSelectedItem(tblLoteamento.getModel().getValueAt(setar, 5).toString());

        txtPesquisarLoteamento.requestFocus();
    }

    private void verificarCodLoteamento() {
               TelaImovel imovel = new TelaImovel();
               
        if (imovel.isVisible()) {
            imovel.toFront();
            imovel.requestFocus();
        }

        String sql = "select * from loteamento where codLoteamento =?";

        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCodLoteamento.getText());
            rs = pst.executeQuery();

            if (rs.next()) {

                if (rs.getString(1).equals(txtCodLoteamento.getText())) {
                    
                  //  TelaImovel imovel = new TelaImovel();
                    TelaPrincipal.DesktopPrincipal.add(imovel);
                    imovel.setVisible(true);
                    imovel.recebendoCodLoteamento(txtCodLoteamento.getText());

                    //imovel.txtCodLoteamentoImovel.setText(txtCodLoteamento.getText());
                    //    imovel.txtCodLoteamentoImovel.setText(imovel.getAccessibleContext().toString());
                    this.dispose();

//                } else if (txtCodLoteamento.getText().isEmpty()) {
//
//
                }
            } else {
                String sql2 = "INSERT INTO loteamento(nomeLoteamento,setorLoteamento,cidadeLoteamento,estadoLoteamento,"
                        + "ufLoteamento) VALUES (?, ?, ?, ?, ?)";
                try {   //31450,00
                    pst = conexao.prepareStatement(sql2);

                    pst.setString(1, txtNomeLoteamento.getText().toUpperCase());
                    pst.setString(2, txtSetorLoteamento.getText().toUpperCase());
                    pst.setString(3, txtCidadeLoteamento.getText().toUpperCase());
                    pst.setString(4, txtEstadoLoteamento.getText().toUpperCase());
                    pst.setString(5, cboULoteamento.getSelectedItem().toString());
                    if (txtNomeLoteamento.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Campo Nome Loteamento é Obrigatório!");
                    } else if (txtSetorLoteamento.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Campo Setor é Obrigatório!");
                    } else if (txtCidadeLoteamento.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Campo Cidade prestação é Obrigatório!");

                    } else if (txtEstadoLoteamento.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Campo Estadp prestação é Obrigatório!");

                    } else {

                        int rowsAfected = pst.executeUpdate();
                        // if (rowsAfected > 0) {
                        //  JOptionPane.showMessageDialog(null, "Loteamento cadastrada com sucesso!", "Cadastro", 1);
//                                txtNomeLoteamento.setText("");
//                                txtSetorLoteamento.setText("");
//                                txtCidadeLoteamento.setText("");
//                                txtEstadoLoteamento.setText("");
//                                cboULoteamento.setSelectedItem("AC");
                        // txtNomeLoteamento.requestFocus();

                        //  }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

               String sql3 = "SELECT codLoteamento FROM loteamento ORDER BY codLoteamento DESC limit 1";
        try {
            pst = conexao.prepareStatement(sql3);
            rs = pst.executeQuery();
            if (rs.next()) {
            //    TelaImovel imovel = new TelaImovel();
                TelaPrincipal.DesktopPrincipal.add(imovel);
                imovel.setVisible(true);
                imovel.recebendoCodLoteamento(rs.getString(1));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro : "+ e);
        }
            }

            JOptionPane.showMessageDialog(null, "Loteamento Inserido com sucesso");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        

        this.dispose();
    
    }
}
