/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.informatica.util;

import br.com.informatica.dal.Conexao;
import br.com.informatica.telas.GerarBoleto;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author edilson
 */
public class GerarBoletoDialog extends javax.swing.JDialog {

    public static GerarBoleto boleto;
    String codigo;
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public GerarBoletoDialog(GerarBoleto parent, boolean modal) {

        this.boleto = parent;
        this.setModal(modal);
        initComponents();
          final JTextField ftf = jTextPesquisarVenda;
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                ftf.requestFocusInWindow();
            }
        });
        
        conexao = Conexao.conector;
    }

    public String getCodigo() {

        return codigo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVendas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextPesquisarVenda = new javax.swing.JTextField();
        jBnInserir = new javax.swing.JButton();
        jBnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Venda Para Gerar Boleto");

        jPanel1.setBackground(new java.awt.Color(204, 240, 240));

        jTableVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod Vend", "ValorPrest", "Nome Cli", "Data Vend", "Rua", "Quad", "Lote", "Loteamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVendas);

        jLabel1.setText("Pesquisar Venda");

        jTextPesquisarVenda.setToolTipText("Digite o nome do cliente ou clique na barra de espaço");
        jTextPesquisarVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextPesquisarVendaKeyReleased(evt);
            }
        });

        jBnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/informatica/icones/inserir.png"))); // NOI18N
        jBnInserir.setToolTipText("Insere o código do cliente na tela de boleto");
        jBnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnInserirActionPerformed(evt);
            }
        });

        jBnFechar.setBackground(new java.awt.Color(204, 240, 240));
        jBnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/informatica/icones/fechar2.png"))); // NOI18N
        jBnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jTextPesquisarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jBnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextPesquisarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 990, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPesquisarVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPesquisarVendaKeyReleased
         pesquisarVenda();
    }//GEN-LAST:event_jTextPesquisarVendaKeyReleased

    private void jBnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnInserirActionPerformed

        this.dispose();

    }//GEN-LAST:event_jBnInserirActionPerformed

    private void jBnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBnFecharActionPerformed

    private void jTableVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVendasMouseClicked
        int setar = jTableVendas.getSelectedRow();
        codigo = (jTableVendas.getModel().getValueAt(setar, 0).toString());
    }//GEN-LAST:event_jTableVendasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerarBoletoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerarBoletoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerarBoletoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerarBoletoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GerarBoletoDialog dialog = new GerarBoletoDialog(boleto, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBnFechar;
    private javax.swing.JButton jBnInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVendas;
    private javax.swing.JTextField jTextPesquisarVenda;
    // End of variables declaration//GEN-END:variables

    private void pesquisarVenda() {

        String sql = "SELECT V.codVenda,V.valorPrestacao AS Prestacao,\n" +
"                    Cl.nomeCliente AS Cliente,Cl.telefoneCliente AS Telefone,Cl.cpfCliente AS CPF, \n" +
"                    I.ruaImovel AS Rua, I.quadraImovel AS Quadra,I.loteImovel AS Lote,\n" +
"                    L.nomeLoteamento AS Loteamento, L.cidadeLoteamento AS Cidade\n" +
"                    FROM venda V\n" +
"                    JOIN cliente Cl\n" +
"                    ON Cl.codCliente = V.Cliente_codCliente\n" +
"                    JOIN corretor C\n" +
"                    ON V.corretor_codCorretor = C.codCorretor\n" +
"                    JOIN imovel I\n" +
"                    ON I.codImovel = V.imovel_codImovel\n" +
"                    JOIN loteamento L\n" +
"                    ON L.codLoteamento = I.loteamento_codLoteamento\n" +
"                    WHERE Cl.nomeCliente LIKE ?";
        try {

            pst = conexao.prepareStatement(sql);
            pst.setString(1, "%" + jTextPesquisarVenda.getText() + "%");
            rs = pst.executeQuery();
            jTableVendas.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
}
