/*
ferificar finais de semana e feriados OK!
 */
package br.com.informatica.util;

import br.com.informatica.dal.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author edilson
 */
public class TelaDeTestes extends javax.swing.JFrame {

    Connection conexao = null;
    static PreparedStatement pst = null;
    static ResultSet rs = null;
    static String dataVenc, b, diaDaSemana, feriado, dataVencStr, dataNova;
    static long a;
    static Date dataVencDate;

    public TelaDeTestes() {
        initComponents();
        conexao = Conexao.conector;
        extrairSemana();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeTestes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeTestes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public void extrairSemana() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        List<String> feriados = new ArrayList<>();
        feriados.add("20191011");
        feriados.add("20191012");
        feriados.add("20191013");
        feriados.add("20191021");
        feriados.add("20191022");
        //feriados.add("20191023");
        //   feriados.add("20191014");
        //   feriados.add("20191015");
        //   feriado = "20191014";
        try {
            String sql2 = "SELECT * from lbsy ";
            pst = conexao.prepareStatement(sql2);
            
            rs = pst.executeQuery();

            if (rs.next()) {
                dataVenc = rs.getString(2);

                dataVencDate = sdf.parse(dataVenc);
                dataVencStr = String.valueOf(dataVencDate);
               
                String diaDaSemana = dataVencStr.substring(0, 3);
                if (diaDaSemana.equals("Sat")) {

                    JOptionPane.showMessageDialog(null, "diaDaSemana primeiro if ", diaDaSemana, 1);

                    a = dataVencDate.getTime();
                    a = a + 172800000;
                    dataVencDate = new Date(a);
                    dataVencStr = String.valueOf(dataVencDate);
                    JOptionPane.showMessageDialog(null, "dataVencStr 2 ", dataVencStr, 1);
                    String dataNova = new SimpleDateFormat("yyyyMMdd").format(dataVencDate);
                    JOptionPane.showMessageDialog(null, "dia data Nova ", dataNova, 1);
                    diaDaSemana = dataVencStr.substring(0, 3);
                    for (String feriado : feriados) {
                        if (feriado.equals(dataNova)) {
                            a = dataVencDate.getTime();
                            a = a + 86400000;
                            dataVencDate = new Date(a);
                            dataVencStr = String.valueOf(dataVencDate);
                            JOptionPane.showMessageDialog(null, "dataVencStr 2 ", dataVencStr, 1);
                            dataNova = new SimpleDateFormat("yyyyMMdd").format(dataVencDate);
                            JOptionPane.showMessageDialog(null, "dia data Nova ", dataNova, 1);
                            diaDaSemana = dataVencStr.substring(0, 3);
                        }
                    }
                    dataNova = new SimpleDateFormat("yyyyMMdd").format(dataVencDate);
                }
                if (diaDaSemana.equals("Sun")) {
                    a = dataVencDate.getTime();
                    a = a + 86400000;
                    dataVencDate = new Date(a);
                    dataVencStr = String.valueOf(dataVencDate);
                    JOptionPane.showMessageDialog(null, "dataVencStr 2 ", dataVencStr, 1);
                    dataNova = new SimpleDateFormat("yyyyMMdd").format(dataVencDate);
                    JOptionPane.showMessageDialog(null, "dia data Nova ", dataNova, 1);
                    diaDaSemana = dataVencStr.substring(0, 3);
                    for (String feriado : feriados) {
                        if (feriado.equals(dataNova)) {
                            a = dataVencDate.getTime();
                            a = a + 86400000;
                            dataVencDate = new Date(a);
                            dataVencStr = String.valueOf(dataVencDate);
                            JOptionPane.showMessageDialog(null, "dataVencStr 2 ", dataVencStr, 1);
                            dataNova = new SimpleDateFormat("yyyyMMdd").format(dataVencDate);
                            JOptionPane.showMessageDialog(null, "dia data Nova ", dataNova, 1);
                            diaDaSemana = dataVencStr.substring(0, 3);
                        }
                    }

                }
                //   JOptionPane.showMessageDialog(null, "diaDaSemana segundo if ", diaDaSemana, 1);
                dataNova = new SimpleDateFormat("yyyyMMdd").format(dataVencDate);
                
                for (String feriado : feriados) {
                    if (feriado.equals(dataNova)) {//verificando feriado sozinho
                        JOptionPane.showMessageDialog(null, "DATA NOVA ANTES DO FERIADO SOZINHO 2 ", dataNova, 1);
                        a = dataVencDate.getTime();
                        a = a + 86400000;
                        dataVencDate = new Date(a);
                        dataVencStr = String.valueOf(dataVencDate);
                        JOptionPane.showMessageDialog(null, "dataVencStr 2 ", dataVencStr, 1);
                        dataNova = new SimpleDateFormat("yyyyMMdd").format(dataVencDate);
                        JOptionPane.showMessageDialog(null, "dia data Nova ", dataNova, 1);
                        diaDaSemana = dataVencStr.substring(0, 3);
                        if (diaDaSemana.equals("Sat")) {

                            JOptionPane.showMessageDialog(null, "diaDaSemana primeiro if ", diaDaSemana, 1);

                            a = dataVencDate.getTime();
                            a = a + 172800000;
                            dataVencDate = new Date(a);
                            dataVencStr = String.valueOf(dataVencDate);
                            JOptionPane.showMessageDialog(null, "dataVencStr 2 ", dataVencStr, 1);
                            dataNova = new SimpleDateFormat("yyyyMMdd").format(dataVencDate);
                            JOptionPane.showMessageDialog(null, "dia data Nova ", dataNova, 1);
                            diaDaSemana = dataVencStr.substring(0, 3);
                        }
                    }
                  

                }

            }

        } catch (Exception e) {
        }
    }
}
