/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.informatica.telas;

import static br.com.informatica.telas.TelaSaida.jDateChooserSaida;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author edilson
 */
public class GerarBoleto extends javax.swing.JInternalFrame {

    /**
     * Creates new form GerarBoleto
     */
    public GerarBoleto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooserCellEditor1 = new com.toedter.calendar.JDateChooserCellEditor();
        pnlGerarBoleto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtCalcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextQuantDias = new javax.swing.JTextField();
        jDateDataVenc = new com.toedter.calendar.JDateChooser();
        jDateDataPag = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gerar Boleto");

        pnlGerarBoleto.setBackground(new java.awt.Color(204, 240, 240));

        jLabel1.setText("DtVenc");

        jLabel2.setText("DtPag");

        jBtCalcular.setText("Calcular");
        jBtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCalcularActionPerformed(evt);
            }
        });

        jLabel3.setText("Quanti Dias");

        javax.swing.GroupLayout pnlGerarBoletoLayout = new javax.swing.GroupLayout(pnlGerarBoleto);
        pnlGerarBoleto.setLayout(pnlGerarBoletoLayout);
        pnlGerarBoletoLayout.setHorizontalGroup(
            pnlGerarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGerarBoletoLayout.createSequentialGroup()
                .addGroup(pnlGerarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGerarBoletoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(pnlGerarBoletoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(pnlGerarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextQuantDias)
                    .addComponent(jDateDataVenc, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jDateDataPag, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jBtCalcular)
                .addGap(128, 128, 128))
        );
        pnlGerarBoletoLayout.setVerticalGroup(
            pnlGerarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGerarBoletoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlGerarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGerarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBtCalcular)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jDateDataPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlGerarBoletoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jDateDataVenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77)
                .addGroup(pnlGerarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextQuantDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(340, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGerarBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGerarBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 970, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCalcularActionPerformed
        calcularQuantDias();
    }//GEN-LAST:event_jBtCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCalcular;
    private com.toedter.calendar.JDateChooserCellEditor jDateChooserCellEditor1;
    private com.toedter.calendar.JDateChooser jDateDataPag;
    private com.toedter.calendar.JDateChooser jDateDataVenc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextQuantDias;
    private javax.swing.JPanel pnlGerarBoleto;
    // End of variables declaration//GEN-END:variables

    private void calcularQuantDias() {
        try {
            String dataVencStr = "";
            String dataPagStr = "";
            //  SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
            SimpleDateFormat sdf = new SimpleDateFormat("ddMMyyyy");
//        java.util.Date dataVenc = jDateDataVenc.getDate();
//        dataVencStr = sdf.format(dataVenc);
//        String anoVenc = dataVencStr.substring(0,4);
//        String mesVenc = dataVencStr.substring(4,6);
//        String diaVenc = dataVencStr.substring(6);
//        ////////////////////////////////////////////////
//        java.util.Date dataPag = jDateDataPag.getDate();
//        dataPagStr = sdf.format(dataPag);
//        String anoPag = dataPagStr.substring(0,4);
//        String mesPag = dataPagStr.substring(4,6);
//        String diaPag = dataPagStr.substring(6);
//        ////////////////////////////////////////////////
//        LocalDate dataVencimento = LocalDate.of(Integer.parseInt(anoVenc), Integer.parseInt(mesVenc), Integer.parseInt(diaVenc));
//        LocalDate dataPagamento = LocalDate.of(Integer.parseInt(anoPag), Integer.parseInt(mesPag), Integer.parseInt(diaPag));
//        
//        Period periodo = Period.between(dataVencimento, dataPagamento);
//        int quantDias = periodo.getDays();
//        System.out.println("Quantidade de Dias: "+quantDias);
//        jTextQuantDias.setText(String.valueOf(quantDias));
//        System.out.println("Data Venc : " + dataVencStr);
//        System.out.println("Data Pagamento : " + dataPagStr);
            java.util.Date receDataPag = jDateDataPag.getDate();
            System.out.println("Date da classe boleto "+ receDataPag);
            java.util.Date receDataVenc = jDateDataVenc.getDate();
            String dataPagStrg = "";
            String dataVencStrg = "";

            dataPagStrg = sdf.format(receDataPag);//FORMATANDO UM DATE E COLOCANDO EM UMA STRING
            System.out.println("dataPagStrg "+dataPagStrg);
            Date dateDataPag = sdf.parse(dataPagStrg);//PASSANDO A STRING DE VOLTA PARA DATE
            dataVencStrg = sdf.format(receDataVenc);//FORMATANDO UM DATE E COLOCANDO EM UMA STRING
            System.out.println("dataVencStrg "+dataVencStrg);
            Date dateDataVenc = sdf.parse(dataVencStrg);//PASSANDO A STRING DE VOLTA PARA DATE
            long quantDias = (dateDataPag.getTime() - dateDataVenc.getTime());
            long quantTotalDias = TimeUnit.DAYS.convert(quantDias, TimeUnit.MILLISECONDS);

            jTextQuantDias.setText(String.valueOf(quantTotalDias));
            /////////////////////////////////////////////////

        } catch (ParseException ex) {
            Logger.getLogger(GerarBoleto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
