/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.informatica.telas;

//import br.com.informatica.dal.ConexaoBanco;
import br.com.informatica.dal.Conexao;
import br.com.informatica.util.TelaLbSy;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author edilson
 */
public class TelaUsuarios1 extends javax.swing.JInternalFrame {

    PreparedStatement pst = null;
    Connection conexao = null;
    ResultSet rs = null;

    public TelaUsuarios1() {

        initComponents();
        //conexao = ConexaoBanco.conector;
        conexao = Conexao.conector;
        //tecla de atalho para liberar o sistema
        jBtLiberarSistema.setMnemonic(KeyEvent.VK_L);
        jBtLiberarSistema.setOpaque(false);
        jBtLiberarSistema.setContentAreaFilled(false);
        jBtLiberarSistema.setBorderPainted(false);
    //    TelaLogin login = new TelaLogin();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPesquisaUsuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        txtIdUsuario = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboPerfil = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnAdicionarUsuario = new javax.swing.JButton();
        btnAlterarUsuario = new javax.swing.JButton();
        btnLimparUsuario = new javax.swing.JButton();
        btnApagarUsuario = new javax.swing.JButton();
        btnUsuarioImprimir = new javax.swing.JButton();
        txtPasswordConfirma = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtPassword1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jBtLiberarSistema = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro Usuario");
        setPreferredSize(new java.awt.Dimension(851, 610));

        jLabel1.setText("* Campos Obrigatórios");

        jLabel2.setText("Pesquisa");

        txtPesquisaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaUsuarioKeyReleased(evt);
            }
        });

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Usuario", "Nome Usuario", "Telefone", "Login", "Senha", "Perfil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuario);
        if (tblUsuario.getColumnModel().getColumnCount() > 0) {
            tblUsuario.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblUsuario.getColumnModel().getColumn(1).setMinWidth(200);
            tblUsuario.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblUsuario.getColumnModel().getColumn(2).setMinWidth(20);
            tblUsuario.getColumnModel().getColumn(2).setPreferredWidth(20);
            tblUsuario.getColumnModel().getColumn(3).setMinWidth(15);
            tblUsuario.getColumnModel().getColumn(3).setPreferredWidth(15);
            tblUsuario.getColumnModel().getColumn(4).setPreferredWidth(15);
            tblUsuario.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        jLabel3.setText("I Usuario");

        jLabel4.setText("* Nome Usuario");

        jLabel5.setText("Telefone");

        jLabel6.setText("*Confirma Senha");

        jLabel7.setText("*Login");

        txtIdUsuario.setEnabled(false);

        jLabel9.setText("* Nome ");

        cboPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin\t", " ", " " }));
        cboPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPerfilActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        btnAdicionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/informatica/icones/create.png"))); // NOI18N
        btnAdicionarUsuario.setToolTipText("Adiciona Usuario");
        btnAdicionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionarUsuario);

        btnAlterarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/informatica/icones/update.png"))); // NOI18N
        btnAlterarUsuario.setToolTipText("Altera Usuario");
        btnAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterarUsuario);

        btnLimparUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/informatica/icones/clear.png"))); // NOI18N
        btnLimparUsuario.setToolTipText("Liimpa Usuario");
        btnLimparUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimparUsuario);

        btnApagarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/informatica/icones/delete.png"))); // NOI18N
        btnApagarUsuario.setToolTipText("Deleta Usuario");
        btnApagarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnApagarUsuario);

        btnUsuarioImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/informatica/icones/impressora.png"))); // NOI18N
        btnUsuarioImprimir.setToolTipText("Relatorio Usuario");
        jPanel1.add(btnUsuarioImprimir);

        txtPasswordConfirma.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordConfirmaFocusLost(evt);
            }
        });
        txtPasswordConfirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPasswordConfirmaMouseExited(evt);
            }
        });

        jLabel10.setText("Perfil");

        jLabel8.setText("*Senha");

        jBtLiberarSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLiberarSistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(45, 45, 45)
                                .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(12, 12, 12)
                                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBtLiberarSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3))
                                .addGap(41, 41, 41)
                                .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)))
                        .addComponent(txtPasswordConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtPesquisaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPesquisaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtPasswordConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jBtLiberarSistema)
                .addGap(19, 19, 19))
        );

        setBounds(0, 0, 970, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarUsuarioActionPerformed
        String senha = txtPassword1.getText().toString();
        String confirmaSenha = txtPasswordConfirma.getText().toString();
        boolean compara = senha.equals(confirmaSenha);

        if (compara == false) {
            JOptionPane.showMessageDialog(null, "As Senhas não Coicidem");
        } else {
            adcionarUsuario();
        }


    }//GEN-LAST:event_btnAdicionarUsuarioActionPerformed

    private void txtPesquisaUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaUsuarioKeyReleased
        pesquisarUsuario();
    }//GEN-LAST:event_txtPesquisaUsuarioKeyReleased

    private void tblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseClicked
        setarCampos();
    }//GEN-LAST:event_tblUsuarioMouseClicked

    private void btnAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarUsuarioActionPerformed
        String senha = txtPassword1.getText().toString();
        String confirmaSenha = txtPasswordConfirma.getText().toString();
        boolean compara = senha.equals(confirmaSenha);

        if (compara == false) {
            JOptionPane.showMessageDialog(null, "As Senhas não Coicidem");
        } else {
            alterarUsuario();
            limparUsuario();
        }

    }//GEN-LAST:event_btnAlterarUsuarioActionPerformed

    private void btnLimparUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparUsuarioActionPerformed
        txtIdUsuario.setText(null);
        txtNomeUsuario.setText(null);
        txtTelefone.setText(null);
        txtLogin.setText(null);
        txtPasswordConfirma.setText(null);
        btnAdicionarUsuario.setEnabled(true);
        txtPesquisaUsuario.requestFocus();
        limparUsuario();
    }//GEN-LAST:event_btnLimparUsuarioActionPerformed

    private void btnApagarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarUsuarioActionPerformed
        deletarUsuario();
    }//GEN-LAST:event_btnApagarUsuarioActionPerformed

    private void cboPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPerfilActionPerformed

    private void txtPasswordConfirmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordConfirmaMouseExited
        verificarSenhas();
    }//GEN-LAST:event_txtPasswordConfirmaMouseExited

    private void txtPasswordConfirmaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordConfirmaFocusLost
        verificarSenhas();
    }//GEN-LAST:event_txtPasswordConfirmaFocusLost

    private void jBtLiberarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLiberarSistemaActionPerformed
       atualizaLbSy();
    }//GEN-LAST:event_jBtLiberarSistemaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarUsuario;
    private javax.swing.JButton btnAlterarUsuario;
    private javax.swing.JButton btnApagarUsuario;
    private javax.swing.JButton btnLimparUsuario;
    private javax.swing.JButton btnUsuarioImprimir;
    private javax.swing.JComboBox<String> cboPerfil;
    public static javax.swing.JButton jBtLiberarSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtLogin;
    public javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPasswordConfirma;
    private javax.swing.JTextField txtPesquisaUsuario;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void adcionarUsuario() {
        //  Connection conexao = null;
        PreparedStatement pst = null;
        String sql = "INSERT INTO usuarios (nomeUsu,telefone,login,senha,perfil) VALUES (?, ?, ?, ?, ?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtNomeUsuario.getText());
            pst.setString(2, txtTelefone.getText());
            pst.setString(3, txtLogin.getText());
            pst.setString(4, String.valueOf(txtPasswordConfirma.getPassword()));
            pst.setString(5, cboPerfil.getSelectedItem().toString());

            // validaçao dos campos obrigatórios
            if (txtNomeUsuario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo Usuario é Obrigatório!");
            } else if (txtLogin.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo Login é Obrigatório!");
            } else if (txtPasswordConfirma.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo Senha é Obrigatório!");
            } else {
                int rowsAfected = pst.executeUpdate();

                if (rowsAfected > 0) {
                    JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!", "Cadastro", 1);

                    txtIdUsuario.setText("");
                    txtNomeUsuario.setText("");
                    txtTelefone.setText("");
                    txtLogin.setText("");
                    txtPasswordConfirma.setText("");
                    cboPerfil.setSelectedIndex(1);
                    txtIdUsuario.requestFocus();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void pesquisarUsuario() {
        String sql = "SELECT * from usuarios WHERE  nomeUsu LIKE ? AND nomeUsu <> 'Super' ";

        try {
            //podemos colocar o Conexao.conexao aqui dentro do metodo ou dentro do construtor
            //para que o codigo seja usado por toda a classe
            pst = conexao.prepareStatement(sql);
            pst.setString(1, "%" + txtPesquisaUsuario.getText() + "%");
            rs = pst.executeQuery();
            tblUsuario.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void setarCampos() {
        int setar = tblUsuario.getSelectedRow();
        txtIdUsuario.setText(tblUsuario.getModel().getValueAt(setar, 0).toString());
        txtNomeUsuario.setText(tblUsuario.getModel().getValueAt(setar, 1).toString());
        txtTelefone.setText(tblUsuario.getModel().getValueAt(setar, 2).toString());
        txtLogin.setText(tblUsuario.getModel().getValueAt(setar, 3).toString());
        txtPassword1.setText(tblUsuario.getModel().getValueAt(setar, 4).toString());
        txtPasswordConfirma.setText(tblUsuario.getModel().getValueAt(setar, 4).toString());
        cboPerfil.setSelectedItem(tblUsuario.getModel().getValueAt(setar, 5).toString());
//        cboInserirTipoProd.setSelectedIndex((int) tblProdutos.getModel().getValueAt(setar, 2));

        btnAdicionarUsuario.setEnabled(false);
        txtPesquisaUsuario.requestFocus();
        //  txtLucro.setText(String.valueOf(lucro));
    }

    private void alterarUsuario() {
        String sql = "update usuarios set nomeUsu=?,telefone=?,login=?,senha=?,perfil=? where idUsuario=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtNomeUsuario.getText());
            pst.setString(2, txtTelefone.getText());
            pst.setString(3, txtLogin.getText());
            pst.setString(4, txtPasswordConfirma.getText());
            pst.setString(5, cboPerfil.getSelectedItem().toString());
            pst.setString(6, txtIdUsuario.getText());
            if (txtIdUsuario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo ID é Obrigatório!");
            } else if (txtNomeUsuario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo Nome é Obrigatório!");
            } else if (txtLogin.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo Login é Obrigatório!");
            } else if (txtPasswordConfirma.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo Senha é Obrigatório!");
            } else {

                //a linha abaixa atualiza os dados da tabela com os dados do formulario
                //OBS.: o comando exceuteUpdate(), é utilizado tanto para atualizar 
                //como também para adcionar
                int rowsAfected = pst.executeUpdate();
                if (rowsAfected > 0) {
                    JOptionPane.showMessageDialog(null, "Dados Alterado com Sucesso!");
                    txtIdUsuario.setText(null);
                    txtNomeUsuario.setText(null);
                    txtTelefone.setText(null);
                    txtLogin.setText(null);
                    txtPasswordConfirma.setText(null);
                    btnAdicionarUsuario.setEnabled(true);

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void limparUsuario() {
        String sql2 = "select * from usuarios where nomeUsu = 'XXXX' ";
        try {
            pst = conexao.prepareStatement(sql2);
            rs = pst.executeQuery();
            tblUsuario.setModel(DbUtils.resultSetToTableModel(rs));
            tblUsuario.isValid();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void deletarUsuario() {
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a remoção do usuário? " + txtNomeUsuario.getText(), "Atenção", JOptionPane.YES_NO_OPTION);
        //se confirmar for = YES_OPTION, o comando sql será executado, se txtUsuNom.getText(),
        //for Empty significa que não ha usuario com esse ID
        if (confirma == JOptionPane.YES_OPTION) {

            String sql = "DELETE FROM usuarios WHERE idUsuario = ?";
            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, txtIdUsuario.getText());
                int rowsAffected = pst.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Usuario Removido com Sucesso!");
                    txtIdUsuario.setText(null);
                    txtNomeUsuario.setText(null);
                    txtTelefone.setText(null);
                    txtLogin.setText(null);
                    txtPasswordConfirma.setText(null);
                    txtPassword1.setText(null);
                    btnAdicionarUsuario.setEnabled(true);
                    txtPesquisaUsuario.requestFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    private void verificarSenhas() {
        String senha = txtPassword1.getText().toString();
        String confirmaSenha = txtPasswordConfirma.getText().toString();
        System.out.println("Senha: " + senha);
        System.out.println("Confirma Senha: " + confirmaSenha);
        boolean compara = senha.equals(confirmaSenha);
        if (!txtPasswordConfirma.getText().isEmpty()) {
            if (compara == false) {
                JOptionPane.showMessageDialog(null, "As Senhas não Coicidem");
            }
        }

    }

    private void atualizaLbSy() {
        TelaLbSy lbSy = new TelaLbSy();
        lbSy.setVisible(true);
    }

  
}
